### ISSUE TITLE
ChainData ScriptableObject does not align with Eidolon/ProjectSetup after an SDK update and wallet chain not set when initializing an EMBEDDED WALLET

### ISSUE THREAD

**Issue by kyle789xbl** [TheGreatAxios/issues#1]
Eidolon/ProjectSetup continues to display the last active chain, even though the ChainData asset has been updated. Consequently, initializing a new wallet using EmbeddedWallet does not seem to connect to the correct chain when using a chain and provider

Platform : LINUX HEADLESS SERVER BUILD

chain : AVAX 
How To Reproduce 

build a headless server with a wallet and test the implementation below and make a call to the chain or send a transaction and log it

```

public EmbeddedWallet ServerWallet;
public SmartContract Contract;
string abi = []; //add the abi 

async void Start(){
#if UNITY_SERVER || !UNITY_ANDROID && !UNITY_WEBGL
        ServerWallet = new EmbeddedWallet("PUT YOUR PRIVATE KEY HERE", "43114", new JsonRpcProvider(MainNetRPCServer)); 
        SnowScanURL = "https://snowscan.xyz/tx/";
        Contract = new SmartContract(MainNetContractAddress, abi, ServerWallet);
#endif


try call function on the desired chain from the init Contract 
}

**Comment by 0xRetroDev** [comment]
Thanks for the report @kyle789xbl ! 

The provider issue has been fixed and the project setup window has been improved to persist both popular chain data, but also add custom chain data to your dropdown and persist it between unity sessions.

**Comment by 0xRetroDev** [comment]
@TheGreatAxios  For review
